/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author iduras
 */
public class OdabirBojeZarulje extends javax.swing.JFrame {

    static OdabirBojeZarulje noviProzor = new OdabirBojeZarulje();
    public static String odabranaBoja = "ZaruljaONWH";
    /**
     * Creates new form OdabirBoje
     */
    public OdabirBojeZarulje() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupOdabirBojaZaruljeBoje = new javax.swing.ButtonGroup();
        jRadioButtonOdabirBojeZaruljeCyan = new javax.swing.JRadioButton();
        jRadioButtonOdabirBojeZaruljeWhite = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButtonOdabirBojeZaruljeOdaberi = new javax.swing.JButton();
        jRadioButtonOdabirBojeZaruljeGreen = new javax.swing.JRadioButton();
        jRadioButtonOdabirBojeZaruljeBlue = new javax.swing.JRadioButton();
        jRadioButtonOdabirBojeZaruljeRed = new javax.swing.JRadioButton();
        jRadioButtonOdabirBojeZaruljeMagenta = new javax.swing.JRadioButton();
        jRadioButtonOdabirBojeZaruljeYellow = new javax.swing.JRadioButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Odabir boje žarulje");
        setResizable(false);

        buttonGroupOdabirBojaZaruljeBoje.add(jRadioButtonOdabirBojeZaruljeCyan);
        jRadioButtonOdabirBojeZaruljeCyan.setText("cyan");
        jRadioButtonOdabirBojeZaruljeCyan.setActionCommand("ZaruljaONCyanWH");

        buttonGroupOdabirBojaZaruljeBoje.add(jRadioButtonOdabirBojeZaruljeWhite);
        jRadioButtonOdabirBojeZaruljeWhite.setText("bijela");
        jRadioButtonOdabirBojeZaruljeWhite.setSelected(true);
        jRadioButtonOdabirBojeZaruljeWhite.setActionCommand("ZaruljaONWhiteWH");

        jTextField1.setBackground(new java.awt.Color(0, 255, 255));
        jTextField1.setEnabled(false);

        jTextField2.setEnabled(false);
        jTextField2.setBackground(new java.awt.Color(255, 255, 255) );

        jButtonOdabirBojeZaruljeOdaberi.setText("Odaberi");
        jButtonOdabirBojeZaruljeOdaberi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdabirBojeZaruljeOdaberiActionPerformed(evt);
            }
        });

        buttonGroupOdabirBojaZaruljeBoje.add(jRadioButtonOdabirBojeZaruljeGreen);
        jRadioButtonOdabirBojeZaruljeGreen.setText("zelena");
        jRadioButtonOdabirBojeZaruljeGreen.setActionCommand("ZaruljaONGreenWH");

        buttonGroupOdabirBojaZaruljeBoje.add(jRadioButtonOdabirBojeZaruljeBlue);
        jRadioButtonOdabirBojeZaruljeBlue.setText("plava");
        jRadioButtonOdabirBojeZaruljeBlue.setActionCommand("ZaruljaONBlueWH");

        buttonGroupOdabirBojaZaruljeBoje.add(jRadioButtonOdabirBojeZaruljeRed);
        jRadioButtonOdabirBojeZaruljeRed.setText("crvena");
        jRadioButtonOdabirBojeZaruljeRed.setActionCommand("ZaruljaONRedWH");

        buttonGroupOdabirBojaZaruljeBoje.add(jRadioButtonOdabirBojeZaruljeMagenta);
        jRadioButtonOdabirBojeZaruljeMagenta.setText("magenta");
        jRadioButtonOdabirBojeZaruljeMagenta.setActionCommand("ZaruljaONMagentaWH");

        buttonGroupOdabirBojaZaruljeBoje.add(jRadioButtonOdabirBojeZaruljeYellow);
        jRadioButtonOdabirBojeZaruljeYellow.setText("yellow");
        jRadioButtonOdabirBojeZaruljeYellow.setActionCommand("ZaruljaONYellowWH");

        jTextField3.setBackground(new java.awt.Color(255, 0, 255));
        jTextField3.setEnabled(false);

        jTextField4.setBackground(new java.awt.Color(255, 255, 0));
        jTextField4.setEnabled(false);

        jTextField5.setBackground(new java.awt.Color(255, 0, 0));
        jTextField5.setEnabled(false);

        jTextField6.setBackground(new java.awt.Color(0, 255, 0));
        jTextField6.setEnabled(false);

        jTextField7.setBackground(new java.awt.Color(0, 0, 255));
        jTextField7.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonOdabirBojeZaruljeWhite)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jRadioButtonOdabirBojeZaruljeCyan)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jRadioButtonOdabirBojeZaruljeMagenta)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jRadioButtonOdabirBojeZaruljeYellow)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButtonOdabirBojeZaruljeOdaberi))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonOdabirBojeZaruljeBlue)
                            .addComponent(jRadioButtonOdabirBojeZaruljeRed)
                            .addComponent(jRadioButtonOdabirBojeZaruljeGreen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonOdabirBojeZaruljeWhite)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonOdabirBojeZaruljeCyan)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonOdabirBojeZaruljeRed))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonOdabirBojeZaruljeMagenta)
                            .addComponent(jRadioButtonOdabirBojeZaruljeGreen)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonOdabirBojeZaruljeYellow)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonOdabirBojeZaruljeBlue)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jButtonOdabirBojeZaruljeOdaberi)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOdabirBojeZaruljeOdaberiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdabirBojeZaruljeOdaberiActionPerformed
        switch(buttonGroupOdabirBojaZaruljeBoje.getSelection().getActionCommand()){
            case "ZaruljaONWhiteWH":{
                Pocetna.jButtonRasvjetaZaruljaOdabirBoje.setBackground(new java.awt.Color(255, 255, 255));
                odabranaBoja = "ZaruljaONWhiteWH";
                break;
            }
        
            case "ZaruljaONCyanWH":{
                Pocetna.jButtonRasvjetaZaruljaOdabirBoje.setBackground(new java.awt.Color(0, 255, 255));
                odabranaBoja = "ZaruljaONCyanWH";
                break;
            }
            
            case "ZaruljaONMagentaWH":{
                Pocetna.jButtonRasvjetaZaruljaOdabirBoje.setBackground(new java.awt.Color(255, 0, 255));
                odabranaBoja = "ZaruljaONMagentaWH";
                break;
            }
            
            case "ZaruljaONYellowWH":{
                Pocetna.jButtonRasvjetaZaruljaOdabirBoje.setBackground(new java.awt.Color(255, 255, 0));
                odabranaBoja = "ZaruljaONYellowWH";
                break;
            }
            
            case "ZaruljaONRedWH":{
                Pocetna.jButtonRasvjetaZaruljaOdabirBoje.setBackground(new java.awt.Color(255, 0, 0));
                odabranaBoja = "ZaruljaONRedWH";
                break;
            }
            
            case "ZaruljaONGreenWH":{
                Pocetna.jButtonRasvjetaZaruljaOdabirBoje.setBackground(new java.awt.Color(0, 255, 0));
                odabranaBoja = "ZaruljaONGreenWH";
                break;
            }
            
            case "ZaruljaONBlueWH":{
                Pocetna.jButtonRasvjetaZaruljaOdabirBoje.setBackground(new java.awt.Color(0, 0, 255));
                odabranaBoja = "ZaruljaONBlueWH";
                break;
            }
            
            default:{
                odabranaBoja = "ZaruljaONWH";
                break;
            }
        
        }
        noviProzor.setVisible(false);
    }//GEN-LAST:event_jButtonOdabirBojeZaruljeOdaberiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OdabirBojeZarulje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OdabirBojeZarulje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OdabirBojeZarulje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OdabirBojeZarulje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new OdabirBojeZarulje().setVisible(true);
            noviProzor.setVisible(true);
            }
        });
    }

    public String getOdabranaBoja() {
        return odabranaBoja;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupOdabirBojaZaruljeBoje;
    private javax.swing.JButton jButtonOdabirBojeZaruljeOdaberi;
    private javax.swing.JRadioButton jRadioButtonOdabirBojeZaruljeBlue;
    private javax.swing.JRadioButton jRadioButtonOdabirBojeZaruljeCyan;
    private javax.swing.JRadioButton jRadioButtonOdabirBojeZaruljeGreen;
    private javax.swing.JRadioButton jRadioButtonOdabirBojeZaruljeMagenta;
    private javax.swing.JRadioButton jRadioButtonOdabirBojeZaruljeRed;
    private javax.swing.JRadioButton jRadioButtonOdabirBojeZaruljeWhite;
    private javax.swing.JRadioButton jRadioButtonOdabirBojeZaruljeYellow;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
