/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controler.Dretva;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import model.Tajmer;

/**
 *
 * @author iduras
 */
public class Pocetna extends javax.swing.JFrame {

    /**
     * Creates new form pocetna
     */
    public Pocetna() {
        
        initComponents();
    }

    Tajmer tajmerZaPoruke = new Tajmer(0, 0, "");
    
    boolean lampicaUkljucena = true;
    boolean oznaciSve = true;
    public static List<List<Tajmer>> listaListaTajmera = new ArrayList<List<Tajmer>>();
    public static List<Tajmer> listaTajmeraLampice = new ArrayList<Tajmer>();
    public static List<Tajmer> listaTajmeraStekera = new ArrayList<Tajmer>();
    public static List<Tajmer> listaTajmeraMasine = new ArrayList<Tajmer>();
    public static List<Tajmer> listaTajmeraZarulje = new ArrayList<Tajmer>();
    static Dretva dretva = Dretva.getDretva();    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPoruka = new javax.swing.JTextPane();
        jTabbedPaneLog = new javax.swing.JTabbedPane();
        jPanelUticnice = new javax.swing.JPanel();
        jRadioButtonUticniceLampicaON = new javax.swing.JRadioButton();
        jRadioButtonUticniceLampicaOFF = new javax.swing.JRadioButton();
        jTextUticniceLampicaMin = new javax.swing.JTextField();
        jTextUticniceLampicaSec = new javax.swing.JTextField();
        jButtonUticniceLampicaPokreni = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButtonUticniceStekerON = new javax.swing.JRadioButton();
        jRadioButtonUticniceStekerOFF = new javax.swing.JRadioButton();
        jTextUticniceStekerMin = new javax.swing.JTextField();
        jTextUticniceStekerSec = new javax.swing.JTextField();
        jButtonUticniceStekerPokreni = new javax.swing.JButton();
        jCheckBoxUticniceLampica = new javax.swing.JCheckBox();
        jCheckBoxUticniceSteker = new javax.swing.JCheckBox();
        jButtonUticniceUkljuciOznaceneUticnice = new javax.swing.JButton();
        jButtonUticniceIskljuciOznaceneUticnice = new javax.swing.JButton();
        jButtonUticniceOznaciSve = new javax.swing.JButton();
        jCheckBoxUticniceMasina = new javax.swing.JCheckBox();
        jRadioButtonUticniceMasinaON = new javax.swing.JRadioButton();
        jRadioButtonUticniceMasinaOFF = new javax.swing.JRadioButton();
        jButtonMasinaPokreni = new javax.swing.JButton();
        jTextFieldUticniceMasinaMin = new javax.swing.JTextField();
        jTextFieldUticniceMasinaSec = new javax.swing.JTextField();
        jPanelRasvjeta = new javax.swing.JPanel();
        jCheckBoxRasvjetaZarulja = new javax.swing.JCheckBox();
        jRadioButtonRasvjetaZaruljaON = new javax.swing.JRadioButton();
        jRadioButtonRasvjetaZaruljaOFF = new javax.swing.JRadioButton();
        jButtonRasvjetaZaruljaOdabirBoje = new java.awt.Button();
        jButtonRasvjetaZaruljaPokreni = new javax.swing.JButton();
        jTextRasvjetaZaruljaMin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextRasvjetaZaruljaSec = new javax.swing.JTextField();
        jPanelTajmeri = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableTajmeriTablicaTajmera = new javax.swing.JTable();
        jButtonTajmeriObrisiTajmereStekera = new javax.swing.JButton();
        jButtonTajmeriObrisiTajmereLampice = new javax.swing.JButton();
        jButtonTajmeriObrisiTajmereZarulje = new javax.swing.JButton();
        jPanelLog = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableLogTablicaLoga = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Remote");
        setLocation(new java.awt.Point(1518, 187));
        setResizable(false);

        jTextPoruka.setForeground(Color.GREEN);
        jScrollPane1.setViewportView(jTextPoruka);

        buttonGroup1.add(jRadioButtonUticniceLampicaON);
        jRadioButtonUticniceLampicaON.setText("ON");
        jRadioButtonUticniceLampicaON.setSelected(true);
        jRadioButtonUticniceLampicaON.setActionCommand("LampicaONWH");

        buttonGroup1.add(jRadioButtonUticniceLampicaOFF);
        jRadioButtonUticniceLampicaOFF.setText("OFF");
        jRadioButtonUticniceLampicaOFF.setActionCommand("LampicaOFFWH");

        jTextUticniceLampicaMin.setText("0");

        jTextUticniceLampicaSec.setText("0");

        jButtonUticniceLampicaPokreni.setText("pokreni");
        jButtonUticniceLampicaPokreni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUticniceLampicaPokreniActionPerformed(evt);
            }
        });

        jLabel2.setText("min");

        jLabel3.setText("sec");

        buttonGroup2.add(jRadioButtonUticniceStekerON);
        jRadioButtonUticniceStekerON.setText("ON");
        jRadioButtonUticniceStekerON.setSelected(true);
        jRadioButtonUticniceStekerON.setActionCommand("StekerONWH");

        buttonGroup2.add(jRadioButtonUticniceStekerOFF);
        jRadioButtonUticniceStekerOFF.setText("OFF");
        jRadioButtonUticniceStekerOFF.setActionCommand("StekerOFFWH");

        jTextUticniceStekerMin.setText("0");

        jTextUticniceStekerSec.setText("0");

        jButtonUticniceStekerPokreni.setText("pokreni");
        jButtonUticniceStekerPokreni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUticniceStekerPokreniActionPerformed(evt);
            }
        });

        jCheckBoxUticniceLampica.setText("Lampica");

        jCheckBoxUticniceSteker.setText("Šteker");

        jButtonUticniceUkljuciOznaceneUticnice.setText("uključi označene");
        jButtonUticniceUkljuciOznaceneUticnice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUticniceUkljuciOznaceneUticniceActionPerformed(evt);
            }
        });

        jButtonUticniceIskljuciOznaceneUticnice.setText("isključi označene");
        jButtonUticniceIskljuciOznaceneUticnice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUticniceIskljuciOznaceneUticniceActionPerformed(evt);
            }
        });

        jButtonUticniceOznaciSve.setText("označi sve");
        jButtonUticniceOznaciSve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUticniceOznaciSveActionPerformed(evt);
            }
        });

        jCheckBoxUticniceMasina.setText("Mašina");

        buttonGroup3.add(jRadioButtonUticniceMasinaON);
        jRadioButtonUticniceMasinaON.setText("ON");
        jRadioButtonUticniceMasinaON.setSelected(true);
        jRadioButtonUticniceMasinaON.setActionCommand("MasinaONWH");

        buttonGroup3.add(jRadioButtonUticniceMasinaOFF);
        jRadioButtonUticniceMasinaOFF.setText("OFF");
        jRadioButtonUticniceMasinaOFF.setActionCommand("MasinaOFFWH");

        jButtonMasinaPokreni.setText("pokreni");
        jButtonMasinaPokreni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasinaPokreniActionPerformed(evt);
            }
        });

        jTextFieldUticniceMasinaMin.setEditable(false);
        jTextFieldUticniceMasinaMin.setText("0");

        jTextFieldUticniceMasinaSec.setEditable(false);
        jTextFieldUticniceMasinaSec.setText("0");

        javax.swing.GroupLayout jPanelUticniceLayout = new javax.swing.GroupLayout(jPanelUticnice);
        jPanelUticnice.setLayout(jPanelUticniceLayout);
        jPanelUticniceLayout.setHorizontalGroup(
            jPanelUticniceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUticniceLayout.createSequentialGroup()
                .addGroup(jPanelUticniceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUticniceLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelUticniceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonUticniceUkljuciOznaceneUticnice)
                            .addComponent(jButtonUticniceIskljuciOznaceneUticnice)
                            .addComponent(jButtonUticniceOznaciSve)))
                    .addGroup(jPanelUticniceLayout.createSequentialGroup()
                        .addGroup(jPanelUticniceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanelUticniceLayout.createSequentialGroup()
                                .addComponent(jCheckBoxUticniceMasina)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButtonUticniceMasinaON))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelUticniceLayout.createSequentialGroup()
                                .addComponent(jCheckBoxUticniceSteker)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButtonUticniceStekerON))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelUticniceLayout.createSequentialGroup()
                                .addComponent(jCheckBoxUticniceLampica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonUticniceLampicaON)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelUticniceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelUticniceLayout.createSequentialGroup()
                                .addComponent(jRadioButtonUticniceLampicaOFF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelUticniceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextUticniceLampicaMin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGroup(jPanelUticniceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelUticniceLayout.createSequentialGroup()
                                        .addGroup(jPanelUticniceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanelUticniceLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanelUticniceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jTextUticniceLampicaSec, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextUticniceStekerSec, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanelUticniceLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jTextFieldUticniceMasinaSec, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanelUticniceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonUticniceStekerPokreni)
                                            .addComponent(jButtonUticniceLampicaPokreni)
                                            .addComponent(jButtonMasinaPokreni)))
                                    .addGroup(jPanelUticniceLayout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(jLabel3))))
                            .addGroup(jPanelUticniceLayout.createSequentialGroup()
                                .addGroup(jPanelUticniceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonUticniceStekerOFF)
                                    .addComponent(jRadioButtonUticniceMasinaOFF))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelUticniceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldUticniceMasinaMin)
                                    .addComponent(jTextUticniceStekerMin, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelUticniceLayout.setVerticalGroup(
            jPanelUticniceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUticniceLayout.createSequentialGroup()
                .addGroup(jPanelUticniceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelUticniceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxUticniceLampica)
                    .addGroup(jPanelUticniceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonUticniceLampicaON)
                        .addComponent(jRadioButtonUticniceLampicaOFF)
                        .addComponent(jTextUticniceLampicaMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonUticniceLampicaPokreni)
                        .addComponent(jTextUticniceLampicaSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelUticniceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxUticniceSteker)
                    .addComponent(jRadioButtonUticniceStekerON)
                    .addComponent(jRadioButtonUticniceStekerOFF)
                    .addComponent(jTextUticniceStekerMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUticniceStekerPokreni)
                    .addComponent(jTextUticniceStekerSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelUticniceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxUticniceMasina)
                    .addComponent(jRadioButtonUticniceMasinaON)
                    .addComponent(jRadioButtonUticniceMasinaOFF)
                    .addComponent(jTextFieldUticniceMasinaMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMasinaPokreni)
                    .addComponent(jTextFieldUticniceMasinaSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonUticniceUkljuciOznaceneUticnice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonUticniceIskljuciOznaceneUticnice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonUticniceOznaciSve)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextUticniceLampicaSec.getAccessibleContext().setAccessibleDescription("");

        jTabbedPaneLog.addTab("utičnice", jPanelUticnice);

        jCheckBoxRasvjetaZarulja.setText("Žarulja");
        jCheckBoxRasvjetaZarulja.setPreferredSize(new java.awt.Dimension(63, 23));

        buttonGroup4.add(jRadioButtonRasvjetaZaruljaON);
        jRadioButtonRasvjetaZaruljaON.setText("ON");
        jRadioButtonRasvjetaZaruljaON.setSelected(true);
        jRadioButtonRasvjetaZaruljaON.setActionCommand("ZaruljaONWH");

        buttonGroup4.add(jRadioButtonRasvjetaZaruljaOFF);
        jRadioButtonRasvjetaZaruljaOFF.setText("OFF");
        jRadioButtonRasvjetaZaruljaOFF.setActionCommand("ZaruljaOFFWH");

        jButtonRasvjetaZaruljaOdabirBoje.setActionCommand("boja");
        jButtonRasvjetaZaruljaOdabirBoje.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jButtonRasvjetaZaruljaOdabirBoje.setLabel("boja");
        jButtonRasvjetaZaruljaOdabirBoje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRasvjetaZaruljaOdabirBojeActionPerformed(evt);
            }
        });

        jButtonRasvjetaZaruljaPokreni.setText("pokreni");
        jButtonRasvjetaZaruljaPokreni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRasvjetaZaruljaPokreniActionPerformed(evt);
            }
        });

        jTextRasvjetaZaruljaMin.setText("0");

        jLabel4.setText("min");

        jLabel5.setText("sec");

        jTextRasvjetaZaruljaSec.setText("0");

        javax.swing.GroupLayout jPanelRasvjetaLayout = new javax.swing.GroupLayout(jPanelRasvjeta);
        jPanelRasvjeta.setLayout(jPanelRasvjetaLayout);
        jPanelRasvjetaLayout.setHorizontalGroup(
            jPanelRasvjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRasvjetaLayout.createSequentialGroup()
                .addComponent(jCheckBoxRasvjetaZarulja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonRasvjetaZaruljaON)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonRasvjetaZaruljaOFF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRasvjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRasvjetaLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(19, 19, 19))
                    .addComponent(jTextRasvjetaZaruljaMin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelRasvjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRasvjetaLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel5)
                        .addGap(64, 64, 64))
                    .addGroup(jPanelRasvjetaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextRasvjetaZaruljaSec, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRasvjetaZaruljaOdabirBoje, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jButtonRasvjetaZaruljaPokreni)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelRasvjetaLayout.setVerticalGroup(
            jPanelRasvjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRasvjetaLayout.createSequentialGroup()
                .addGroup(jPanelRasvjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRasvjetaLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanelRasvjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRasvjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jCheckBoxRasvjetaZarulja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jRadioButtonRasvjetaZaruljaON)
                                .addComponent(jRadioButtonRasvjetaZaruljaOFF)
                                .addComponent(jTextRasvjetaZaruljaMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextRasvjetaZaruljaSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelRasvjetaLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jButtonRasvjetaZaruljaPokreni))
                            .addComponent(jButtonRasvjetaZaruljaOdabirBoje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelRasvjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)))
                .addGap(335, 335, 335))
        );

        jTabbedPaneLog.addTab("rasvjeta", jPanelRasvjeta);

        jTableTajmeriTablicaTajmera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Događaj", "Minuta", "Sekunda"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableTajmeriTablicaTajmera);
        if (jTableTajmeriTablicaTajmera.getColumnModel().getColumnCount() > 0) {
            jTableTajmeriTablicaTajmera.getColumnModel().getColumn(0).setResizable(false);
            jTableTajmeriTablicaTajmera.getColumnModel().getColumn(1).setResizable(false);
            jTableTajmeriTablicaTajmera.getColumnModel().getColumn(2).setResizable(false);
        }

        jButtonTajmeriObrisiTajmereStekera.setText("Obriši tajmere štekera");
        jButtonTajmeriObrisiTajmereStekera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTajmeriObrisiTajmereStekeraActionPerformed(evt);
            }
        });

        jButtonTajmeriObrisiTajmereLampice.setText("Obriši tajmere lampice");
        jButtonTajmeriObrisiTajmereLampice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTajmeriObrisiTajmereLampiceActionPerformed(evt);
            }
        });

        jButtonTajmeriObrisiTajmereZarulje.setText("Obriši tajmere žarulje");
        jButtonTajmeriObrisiTajmereZarulje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTajmeriObrisiTajmereZaruljeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTajmeriLayout = new javax.swing.GroupLayout(jPanelTajmeri);
        jPanelTajmeri.setLayout(jPanelTajmeriLayout);
        jPanelTajmeriLayout.setHorizontalGroup(
            jPanelTajmeriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
            .addGroup(jPanelTajmeriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTajmeriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTajmeriLayout.createSequentialGroup()
                        .addComponent(jButtonTajmeriObrisiTajmereStekera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonTajmeriObrisiTajmereLampice, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonTajmeriObrisiTajmereZarulje, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTajmeriLayout.setVerticalGroup(
            jPanelTajmeriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTajmeriLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelTajmeriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTajmeriObrisiTajmereStekera)
                    .addComponent(jButtonTajmeriObrisiTajmereLampice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTajmeriObrisiTajmereZarulje)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jTabbedPaneLog.addTab("tajmeri", jPanelTajmeri);

        jTableLogTablicaLoga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Događaj", "Trajanje u sec", "Početak", "Kraj"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableLogTablicaLoga);
        if (jTableLogTablicaLoga.getColumnModel().getColumnCount() > 0) {
            jTableLogTablicaLoga.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTableLogTablicaLoga.getColumnModel().getColumn(1).setPreferredWidth(15);
        }

        javax.swing.GroupLayout jPanelLogLayout = new javax.swing.GroupLayout(jPanelLog);
        jPanelLog.setLayout(jPanelLogLayout);
        jPanelLogLayout.setHorizontalGroup(
            jPanelLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
        );
        jPanelLogLayout.setVerticalGroup(
            jPanelLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
        );

        jTabbedPaneLog.addTab("log", jPanelLog);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPaneLog))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPaneLog, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUticniceOznaciSveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUticniceOznaciSveActionPerformed
        if (oznaciSve) {
            jCheckBoxUticniceLampica.setSelected(oznaciSve);
            jCheckBoxUticniceSteker.setSelected(oznaciSve);
            oznaciSve = false;
        }

        else{
            jCheckBoxUticniceLampica.setSelected(oznaciSve);
            jCheckBoxUticniceSteker.setSelected(oznaciSve);
            oznaciSve = true;
        }
    }//GEN-LAST:event_jButtonUticniceOznaciSveActionPerformed

    private void jButtonUticniceIskljuciOznaceneUticniceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUticniceIskljuciOznaceneUticniceActionPerformed
        Tajmer oznaceniUredjaj = new Tajmer(0, 0, "");

        if (jCheckBoxUticniceLampica.isSelected() || jCheckBoxUticniceSteker.isSelected()) {
            oznaceniUredjaj.provjeraRezultata("Isključivanje označenih uređaja!", 1);
        }

        else{
            oznaceniUredjaj.provjeraRezultata("Nije označen niti jedan uređaj!", 0);
        }
        if (jCheckBoxUticniceLampica.isSelected()) {
            oznaceniUredjaj.setNaredba("LampicaOFFWH");
            oznaceniUredjaj.izvrsi();
        }

        if (jCheckBoxUticniceSteker.isSelected()) {
            oznaceniUredjaj.setNaredba("StekerOFFWH");
            oznaceniUredjaj.izvrsi();
        }
    }//GEN-LAST:event_jButtonUticniceIskljuciOznaceneUticniceActionPerformed

    private void jButtonUticniceUkljuciOznaceneUticniceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUticniceUkljuciOznaceneUticniceActionPerformed

        Tajmer oznaceniUredjaj = new Tajmer(0, 0, "");

        if (jCheckBoxUticniceLampica.isSelected() || jCheckBoxUticniceSteker.isSelected()) {
            oznaceniUredjaj.provjeraRezultata("Uključivanje označenih uređaja!", 1);
        }

        else{
            oznaceniUredjaj.provjeraRezultata("Nije označen niti jedan uređaj!", 0);
        }

        if (jCheckBoxUticniceLampica.isSelected()) {
            oznaceniUredjaj.setNaredba("LampicaONWH");
            oznaceniUredjaj.izvrsi();
        }

        if (jCheckBoxUticniceSteker.isSelected()) {
            oznaceniUredjaj.setNaredba("StekerONWH");
            oznaceniUredjaj.izvrsi();
        }
    }//GEN-LAST:event_jButtonUticniceUkljuciOznaceneUticniceActionPerformed

    /**
     * dodaje tajmer u listu za izvršavanje tajmera štekera
     * @param evt klik na gumb 
     */
    private void jButtonUticniceStekerPokreniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUticniceStekerPokreniActionPerformed
        
        //ako je dretva završila s radom, ponovno ju pokreće
        if (!dretva.isAlive()) {
            dretva.run();
        }

        //provjera jesu li upisani dobri parametri
        try{

            //stvaranje novog trajmera i dodavanje u listu za izvršavanje
            Tajmer tajmer = new Tajmer(Integer.parseInt(jTextUticniceStekerMin.getText()), Integer.parseInt(jTextUticniceStekerSec.getText()), buttonGroup2.getSelection().getActionCommand());
            listaTajmeraStekera.add(tajmer);
            tajmer.provjeraRezultata("Dodan tajmer: " + buttonGroup2.getSelection().getActionCommand(), 1);

        }

        //ako nisu upisani, javlja se porukom
        catch(Exception e){
            tajmerZaPoruke.provjeraRezultata("Upiši minute i sekunde brojkama!", 0);
        }
    }//GEN-LAST:event_jButtonUticniceStekerPokreniActionPerformed

    /**
     * dodaje tajmer u listu za izvršavanje tajmera lampice
     * @param evt klik na gumb 
     */
    private void jButtonUticniceLampicaPokreniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUticniceLampicaPokreniActionPerformed

        //ako je dretva završila s radom, ponovno ju pokreće
        if (!dretva.isAlive()) {
            dretva.run();
        }

        //provjera jesu li upisani dobri parametri
        try{
            Tajmer tajmer = new Tajmer(Integer.parseInt(jTextUticniceLampicaMin.getText()), Integer.parseInt(jTextUticniceLampicaSec.getText()), buttonGroup1.getSelection().getActionCommand());
            listaTajmeraLampice.add(tajmer);
            tajmer.provjeraRezultata("Dodan tajmer: " + buttonGroup1.getSelection().getActionCommand(), 1);

        }

        //ako nisu upisani, javlja se porukom
        catch(Exception e){
            tajmerZaPoruke.provjeraRezultata("Upiši minute i sekunde brojkama!", 0);
        }
    }//GEN-LAST:event_jButtonUticniceLampicaPokreniActionPerformed

    private void jButtonMasinaPokreniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasinaPokreniActionPerformed
        //ako je dretva završila s radom, ponovno ju pokreće
        if (!dretva.isAlive()) {
            dretva.run();
        }

        //provjera jesu li upisani dobri parametri
        try{
            Tajmer tajmer = new Tajmer(0, 0, buttonGroup3.getSelection().getActionCommand());
            listaTajmeraLampice.add(tajmer);
            tajmer.provjeraRezultata("Dodan tajmer: " + buttonGroup3.getSelection().getActionCommand(), 1);

        }

        //ako nisu upisani, javlja se porukom
        catch(Exception e){
            tajmerZaPoruke.provjeraRezultata("Upiši minute i sekunde brojkama!", 0);
        }
    }//GEN-LAST:event_jButtonMasinaPokreniActionPerformed

    private void jButtonTajmeriObrisiTajmereStekeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTajmeriObrisiTajmereStekeraActionPerformed
        for (Iterator<Tajmer> iterator = listaTajmeraStekera.iterator(); iterator.hasNext();) {
            iterator.next();
            iterator.remove();
        }
        
        if (listaTajmeraStekera.isEmpty()) {
            tajmerZaPoruke.provjeraRezultata("Obrisani tajmeri štekera!", 1);
        }
        else{
            tajmerZaPoruke.provjeraRezultata("Tajmeri štekera nisu obrisani!", 0);
        }
    }//GEN-LAST:event_jButtonTajmeriObrisiTajmereStekeraActionPerformed

    private void jButtonTajmeriObrisiTajmereLampiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTajmeriObrisiTajmereLampiceActionPerformed
        for (Iterator<Tajmer> iterator = listaTajmeraLampice.iterator(); iterator.hasNext();) {
            iterator.next();
            iterator.remove();
        }
        
        if (listaTajmeraLampice.isEmpty()) {
            tajmerZaPoruke.provjeraRezultata("Obrisani tajmeri lampice!", 1);
        }
        else{
            tajmerZaPoruke.provjeraRezultata("Tajmeri lampice nisu obrisani!", 0);
        }
    }//GEN-LAST:event_jButtonTajmeriObrisiTajmereLampiceActionPerformed

    private void jButtonRasvjetaZaruljaOdabirBojeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRasvjetaZaruljaOdabirBojeActionPerformed
        String args[] = null;
        OdabirBojeZarulje.main(args);
    }//GEN-LAST:event_jButtonRasvjetaZaruljaOdabirBojeActionPerformed

    private void jButtonRasvjetaZaruljaPokreniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRasvjetaZaruljaPokreniActionPerformed
        //ako je dretva završila s radom, ponovno ju pokreće
        if (!dretva.isAlive()) {
            dretva.run();
        }

        //provjera jesu li upisani dobri parametri
        try{
            
            Tajmer tajmer = new Tajmer(0, 0, "");
            
            if (buttonGroup4.getSelection().getActionCommand().equals("ZaruljaOFFWH")) {
                tajmer = new Tajmer(Integer.parseInt(jTextRasvjetaZaruljaMin.getText()), Integer.parseInt(jTextRasvjetaZaruljaSec.getText()), "ZaruljaOFFWH");
                listaTajmeraZarulje.add(tajmer);
                tajmer.provjeraRezultata("Dodan tajmer: ZaruljaOFFWH", 1);
            } 
            
            else {
                tajmer = new Tajmer(Integer.parseInt(jTextRasvjetaZaruljaMin.getText()), Integer.parseInt(jTextRasvjetaZaruljaSec.getText()), OdabirBojeZarulje.odabranaBoja);
                listaTajmeraZarulje.add(tajmer);
                tajmer.provjeraRezultata("Dodan tajmer: " + OdabirBojeZarulje.odabranaBoja, 1);
            }
            
        }

        //ako nisu upisani, javlja se porukom
        catch(Exception e){
            tajmerZaPoruke.provjeraRezultata("Upiši minute i sekunde brojkama!", 0);
        }
    }//GEN-LAST:event_jButtonRasvjetaZaruljaPokreniActionPerformed

    private void jButtonTajmeriObrisiTajmereZaruljeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTajmeriObrisiTajmereZaruljeActionPerformed
        for (Iterator<Tajmer> iterator = listaTajmeraZarulje.iterator(); iterator.hasNext();) {
            iterator.next();
            iterator.remove();
        }
        
        if (listaTajmeraZarulje.isEmpty()) {
            tajmerZaPoruke.provjeraRezultata("Obrisani tajmeri žarulje!", 1);
        }
        else{
            tajmerZaPoruke.provjeraRezultata("Tajmeri žarulje nisu obrisani!", 0);
        }
    }//GEN-LAST:event_jButtonTajmeriObrisiTajmereZaruljeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        buttonGroup1.setSelected((ButtonModel) jRadioButton1, true);
        
        dretva.start();
        listaListaTajmera.add(listaTajmeraLampice);
        listaListaTajmera.add(listaTajmeraStekera);
        listaListaTajmera.add(listaTajmeraMasine);
        listaListaTajmera.add(listaTajmeraZarulje);
        


        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pocetna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pocetna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pocetna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pocetna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pocetna().setVisible(true);
            }
        });
         
    }  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButtonMasinaPokreni;
    public static java.awt.Button jButtonRasvjetaZaruljaOdabirBoje;
    private javax.swing.JButton jButtonRasvjetaZaruljaPokreni;
    private javax.swing.JButton jButtonTajmeriObrisiTajmereLampice;
    private javax.swing.JButton jButtonTajmeriObrisiTajmereStekera;
    private javax.swing.JButton jButtonTajmeriObrisiTajmereZarulje;
    private javax.swing.JButton jButtonUticniceIskljuciOznaceneUticnice;
    protected javax.swing.JButton jButtonUticniceLampicaPokreni;
    private javax.swing.JButton jButtonUticniceOznaciSve;
    private javax.swing.JButton jButtonUticniceStekerPokreni;
    private javax.swing.JButton jButtonUticniceUkljuciOznaceneUticnice;
    private javax.swing.JCheckBox jCheckBoxRasvjetaZarulja;
    private javax.swing.JCheckBox jCheckBoxUticniceLampica;
    private javax.swing.JCheckBox jCheckBoxUticniceMasina;
    private javax.swing.JCheckBox jCheckBoxUticniceSteker;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanelLog;
    private javax.swing.JPanel jPanelRasvjeta;
    private javax.swing.JPanel jPanelTajmeri;
    private javax.swing.JPanel jPanelUticnice;
    private javax.swing.JRadioButton jRadioButtonRasvjetaZaruljaOFF;
    private javax.swing.JRadioButton jRadioButtonRasvjetaZaruljaON;
    public static javax.swing.JRadioButton jRadioButtonUticniceLampicaOFF;
    public static javax.swing.JRadioButton jRadioButtonUticniceLampicaON;
    private javax.swing.JRadioButton jRadioButtonUticniceMasinaOFF;
    private javax.swing.JRadioButton jRadioButtonUticniceMasinaON;
    private javax.swing.JRadioButton jRadioButtonUticniceStekerOFF;
    private javax.swing.JRadioButton jRadioButtonUticniceStekerON;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPaneLog;
    public static javax.swing.JTable jTableLogTablicaLoga;
    public static javax.swing.JTable jTableTajmeriTablicaTajmera;
    private javax.swing.JTextField jTextFieldUticniceMasinaMin;
    private javax.swing.JTextField jTextFieldUticniceMasinaSec;
    public static javax.swing.JTextPane jTextPoruka;
    private javax.swing.JTextField jTextRasvjetaZaruljaMin;
    private javax.swing.JTextField jTextRasvjetaZaruljaSec;
    private javax.swing.JTextField jTextUticniceLampicaMin;
    private javax.swing.JTextField jTextUticniceLampicaSec;
    private javax.swing.JTextField jTextUticniceStekerMin;
    private javax.swing.JTextField jTextUticniceStekerSec;
    // End of variables declaration//GEN-END:variables
}
